name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node setup (via volta)
        uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
